capture_os: check GHCR_TOKEN secret is empty

diff --git a/.github/workflows/capture_os.yml b/.github/workflows/capture_os.yml
--- a/.github/workflows/capture_os.yml
+++ b/.github/workflows/capture_os.yml
@@ -16,6 +16,12 @@ jobs:
       - name: Cleanup
         run: rm -rf *
 
+      - run: |
+          if [ -z "${{ secrets.GHCR_TOKEN }}" ]; then
+            echo "Missing GHCR token"
+            exit 1
+          fi
+
       - uses: actions/checkout@v4
         with:
           submodules: 'recursive'
